name: Python Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run linters
        working-directory: python
        run: ruff check .