name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Check if python files changed
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            python:
              - 'python/**'

      # Run lint only if python files changed
      - name: Set up Python
        if: steps.filter.outputs.python == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        if: steps.filter.outputs.python == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run linters
        if: steps.filter.outputs.python == 'true'
        working-directory: python
        run: ruff check .
        
      # Skip message (not displayed as a separate job)
      - name: Skip lint
        if: steps.filter.outputs.python != 'true'
        run: echo "No Python changes detected. Skipping lint."