name: TypeScript Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      typescript: ${{ steps.filter.outputs.typescript }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            typescript:
              - 'typescript/**'

  lint:
    name: Lint
    needs: changes
    if: ${{ needs.changes.outputs.typescript == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '9'

      - name: Install dependencies
        working-directory: typescript
        run: pnpm install
      
      - name: Run lint
        working-directory: typescript
        run: pnpm lint
        
  skip:
    name: Lint Skipped
    needs: changes
    if: ${{ needs.changes.outputs.typescript != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip lint
        run: echo "No TypeScript changes detected. Skipping lint."
